name: CI Python Matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install -r requirements.txt
    - run: pytest tests/ -v
      env:
        # Añade esta línea: PYTHONPATH apunta al directorio raíz del repositorio.
        # GitHub Actions clona el repo en GITHUB_WORKSPACE.
        PYTHONPATH: ${{ github.workspace }}

    - name: Verificar app corriendo
      run: |
        timeout 10 python app.py &
        sleep 5
        curl -f http://localhost:5000/health
